Update conf changelog dates, fix indents

diff --git a/Dockerfile.aarch64 b/Dockerfile.aarch64
--- a/Dockerfile.aarch64
+++ b/Dockerfile.aarch64
@@ -66,9 +66,9 @@ RUN \
   php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
   ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" && \
   if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then \
-      >&2 echo 'ERROR: Invalid installer checksum' && \
-      rm composer-setup.php && \
-      exit 1; \
+    >&2 echo 'ERROR: Invalid installer checksum' && \
+    rm composer-setup.php && \
+    exit 1; \
   fi && \
   php composer-setup.php --install-dir=/usr/bin && \
   rm composer-setup.php && \
